shop/myshop/cart/urls.py
from django.urls import path
from . import views

app_name ='cart'
urlpatterns=[
    path('', views.cart_detalle, name='cart_detalle'),
    path('add/<int:producto_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:producto_id>/', views.cart_remove, name='cart_remove'),
]

shop/myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='order')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/myshop/payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
 path('process/', views.payment_process, name='process'),
 path('completed/', views.payment_completed, name='completed'),
 path('canceled/', views.payment_canceled, name='canceled'),
]

shop/myshop/payment/models.py
from django.db import models

# Create your models here.

shop/myshop/payment/views.py
from decimal import Decimal
import stripe
from django.conf import settings
from django.shortcuts import render, redirect, reverse,\
get_object_or_404
from orders.models import Orden

# CREAR UNA INSTANCIA DE STRIPE
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION

# CREAR EL PROCESO DE PAGO
def payment_process(request):
    # OBTENER EL ID DE ACUERDO A LA SESIÓN QUE SE HA GUARDADO
    orden_id = request.session.get('orden_id', None)
    # OBTENER LA ORDEN
    orden = get_object_or_404(Orden, id=orden_id)
    #
    if request.method == 'POST':
        #
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        #
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))
        
        # DATOS DE LA SESIÓN DE PAGO DE STRIPE
        session_data = {
        'mode': 'payment',
        'client_reference_id': orden.id,
        'success_url': success_url,
        'cancel_url': cancel_url,
        'line_items': []
        }

        # AÑADIR ELEMENTOS DEL PEDIDO A LA SESIÓN DE PAGO DE STRIPE
        for item in orden.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.precio * Decimal('100')),
                    'currency': 'mxn',
                    'product_data': {
                        'name': item.producto.nombre,
                    },
                },
                'quantity': item.cantidad,
            })

        # CREAR SESIÓN DE PAGO STRIPE
        session = stripe.checkout.Session.create(**session_data)

        # REDIRIGIR AL FORMULARIO DE PAGO DE STRIPE
        return redirect(session.url, code=303)
    
    else:
        return render(request, 'payment/process.html',locals())
    
def payment_completed(request):
    orden_id = request.session.get('orden_id')
    orden = Orden.objects.get(id=orden_id)
    return render(request, 'payment/completed.html', {'orden': orden})

def payment_canceled(request):
    return render(request, 'payment/canceled.html')

shop/myshop/payment/templates/payment/canceled.html
{% extends "shop/base.html" %}

{% block title %}Pago Cancelado{% endblock %}
 
{% block content %}
    <h1>Su pago no ha sido procesado</h1>
    <p>Ha habido un problema al procesar su pago.</p>
{% endblock %}

shop/myshop/payment/templates/payment/completed.html
{% extends "shop/base.html" %}

{% block title %}
 ¡Gracias Por tu compra!
{% endblock %}

{% block content %}

    <h1>¡Gracias por su pedido!</h1>
    <p>Su pedido se ha realizado correctamente. Su número de pedido es
    <strong>{{ orden.id }}</strong>.</p>
{% endblock %}

shop/myshop/payment/templates/payment/process.html
<!-- EXTENDER NUESTRO ARCHIVO BASE-->
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    Pedido
{% endblock %}

{% block content %}
    <!-- TÍTULO-->
    <h1>Resumen del Pedido</h1>
    <!-- TABLA PARA MOSTRAR TODOS LOS ELEMENTOS AGREGADOS AL CARRITO -->
    <table class="cart">
        <thead>
            <tr>
                <th>Imagen</th>
                <th>Producto</th>
                <th>Precio</th>
                <th>Cantidad</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <!-- MOSTRAR LOS PRODUCTOS AGREGADOS AL CARRITO -->
            {% for item in orden.items.all %}
                <tr class="row{% cycle "1" "2" %}">
                    <td>
                        <img src="{% if item.producto.imagen %}{{ item.producto.imagen.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                    </td>
                    <td>{{ item.producto.nombre }}</td>
                    <td class="num">${{ item.precio }}</td>
                    <td class="num">{{ item.cantidad }}</td>
                    <td class="num">${{ item.get_cost }}</td>
                </tr>
            {% endfor %}
            <tr class="total">
                <td colspan="4">Total</td>
                <td class="num">${{ orden.get_total_cost }}</td>
            </tr>
        </tbody>
    </table>
    <form action="{% url 'payment:process' %}" method="post">
        <input type="submit" value="Pagar">
        {% csrf_token %}
    </form>
    {% endblock %}