shop/myshop/cart/urls.py
from django.urls import path
from . import views

app_name ='cart'
urlpatterns=[
    path('', views.cart_detalle, name='cart_detalle'),
    path('add/<int:producto_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:producto_id>/', views.cart_remove, name='cart_remove'),
]

shop/myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='order')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/myshop/shop/urls.py
from django.urls import path
from . import views

app_name ='shop'
urlpatterns=[
    path('', views.producto_lista, name='producto_lista'),
    path('buscar_productos/', views.buscar_productos, name='buscar_productos'),
    path('<slug:categoria_slug>/', views.producto_lista, name='producto_lista_by_categoria'),
    path('<int:id>/<slug:slug>/', views.producto_detalle, name='producto_detalle'),
]

shop/myshop/users/urls.py
from django.urls import path
from .views import Registro, cerrar_sesion, iniciar_sesion

app_name = 'users'

urlpatterns = [
    path('', Registro.as_view(), name='Usuarios'),
    path('cerrrar_sesion', cerrar_sesion, name='cerrar_sesion'),
    path('iniciar_sesion', iniciar_sesion, name='iniciar_sesion'),
]

shop/myshop/shop/models.py
from django.db import models
from django.urls import reverse

# BD PARA LA CATEGORIA Y PRODUCTOS

# DEFINIENDO LA CATEGORIA DE LOS PRODUCTOS
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    # PERSONALIZAR EL ORDEN, INDEXACIÓN Y NOMBRES
    class Meta:
        ordering = ['nombre']
        indexes = [models.Index(fields=['nombre']),]
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'
    # REGRESAR EL NOMBRE 
    def __str__(self):
        return self.nombre
    # GENERAR LA URL
    def get_absolute_url(self):
        return reverse('shop:producto_lista_by_categoria',
                        args=[self.slug])
# DEFINIENDO  LOS PRODUCTOS
class Producto(models.Model):
    categoria = models.ForeignKey(Categoria, related_name='Productos', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    imagen = models.ImageField(upload_to='productos/%Y/%m/%d', blank=True)
    descripcion = models.TextField(blank=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    disponibilidad = models.BooleanField(default=True)
    existencias = models.PositiveIntegerField(default=0)  # Campo para las existencias del producto
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['nombre']
        indexes = [models.Index(fields=['id', 'slug']),
                   models.Index(fields=['nombre']),
                   models.Index(fields=['-created']),
                   ]

    def __str__(self):
        return self.nombre 
    
    def get_absolute_url(self):
        return reverse('shop:producto_detalle',
                        args=[self.id, self.slug])
    
    @property
    def esta_agotado(self):
        return self.existencias <= 0 

shop/myshop/shop/views.py
from django.shortcuts import render, get_object_or_404, redirect  
from .models import Categoria, Producto
from cart.forms import CartAddProductForm

# Create your views here.

def producto_lista(request, categoria_slug=None):
    categoria = None
    categorias = Categoria.objects.all()
    productos = Producto.objects.filter(disponibilidad=True)

    if categoria_slug:
        categoria = get_object_or_404(Categoria, slug=categoria_slug)
        productos = productos.filter(categoria=categoria)
    return render(request, 
                  'shop/producto/lista.html',
                  {'categoria':categoria,
                   'categorias': categorias,
                   'productos': productos})

def producto_detalle(request, id, slug):
    producto = get_object_or_404(Producto, 
                                 id=id, 
                                 slug=slug, 
                                 disponibilidad=True)
    cart_product_form = CartAddProductForm()

    
    if request.method == 'POST':
        cart_product_form = CartAddProductForm(request.POST, producto=producto)
        if cart_product_form.is_valid():
            # Procesa el formulario y agrega el producto al carrito
            pass
    
    return render(request, 
                  'shop/producto/detalle.html',
                  {'producto':producto,
                   'cart_product_form': cart_product_form})

def buscar_productos(request):
    query = request.GET.get('q')
    resultados = None
    if query:
        resultados = Producto.objects.filter(nombre__icontains=query)
    return render(request, 'shop/producto/buscar_productos.html', {'resultados': resultados, 'query': query})

#http://127.0.0.1:800/

shop/myshop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}BreakFast{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    <!--Favicon (logito de la pestaña) -->
    <link rel="icon" href="{% static "images/refresco-de-hamburguesa.png" %}">
     <!-- TIPOGRAFÍA DE LETRA -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

</head>
<body>
    <!--CABECERAAAA-->
        <div id="subheader">
            <!--LOGO DE LA EMPRESA-->
            <div class="cart">
                <a href="/" class="nombre-logo">Breakfast</a>
            </div>
            <!-- Panel de navegación -->  
            <div class="container-navegacion">
                <!-- FORMULARIO DE BÚSQUEDAD DE PRODUCTOS -->
                <form  action="{% url 'shop:buscar_productos' %}" method="GET" class="d-flex">
                    <input class="form-control" type="search" placeholder="Buscar productos..." aria-label="Search" name="q">
                    <button>
                        <img class="imagenes-subheader" src="{% static "images/archivo-de-busqueda.png" %}" alt="logo"> 
                    </button>
                        
                    
                </form>
            </div>
            
            <!--MOSTRAR SI EL USUARIO HA INICIADO SESIÓN-->
            <div class="inicio">
                <!--VERIFICAR SI EL USUARIO YA ESTA INICIO SESIÓN-->
               {% if user.is_authenticated %}
                        <img class="imagenes-subheader" src="{% static "images/usuario.png" %}" alt="usuario">
                        {{ user.username }} <a class="accesos" href="{% url "users:cerrar_sesion" %}">Cerrar Sesión</a>
                <!--EL USUARIO NO HA INGRESADO-->
               {% else %}
                    <!--INICIAR SESIÓN-->
                    <a  class="accesos" href="{% url "users:iniciar_sesion" %}">
                        Iniciar Sesión
                    </a>
                    <!--REGISTRARSE SI EL USUARIO NO TIENEN UNA CUENTA-->
                    <a class="accesos" href="{% url "users:Usuarios" %}">
                        Registrate
                   </a>
               {% endif %}
            </div>
            <!--CONTROL DE PRODUCTOS AGREGADOS AL CARRITO-->
            <div>
                {% with total_items=cart|length %}
                    {% if total_items > 0 %} 
                        <a href="{% url "cart:cart_detalle" %}">
                            <img class="imagenes-subheader" src="{% static "images/carrito.png" %}" alt="logo"> 
                            <!-- Total de productos en el carrito-->
                            <span class="cart-num">{{ total_items }}</span>
                            </a>
                    {% elif not order %}
                        <a href="{% url "cart:cart_detalle" %}">
                            <img class="imagenes-subheader" src="{% static "images/carrito.png" %}" alt="logo"> 
                            <!-- Total de productos en el carrito-->
                            <span class="cart-num">{{ total_items }}</span>
                        </a>
                    {% endif %}
                {% endwith %}
            </div>
                
        </div>
    
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>