shop/myshop/cart/urls.py
from django.urls import path
from . import views

app_name ='cart'
urlpatterns=[
    path('', views.cart_detalle, name='cart_detalle'),
    path('add/<int:producto_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:producto_id>/', views.cart_remove, name='cart_remove'),
]

shop/myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='order')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/myshop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('created/', views.order_created, name='order_created'),
]

shop/myshop/shop/urls.py
from django.urls import path
from . import views

app_name ='shop'
urlpatterns=[
    path('', views.producto_lista, name='producto_lista'),
    path('buscar_productos/', views.buscar_productos, name='buscar_productos'),
    path('<slug:categoria_slug>/', views.producto_lista, name='producto_lista_by_categoria'),
    path('<int:id>/<slug:slug>/', views.producto_detalle, name='producto_detalle'),
]

shop/myshop/users/urls.py
from django.urls import path
from .views import Registro, cerrar_sesion, iniciar_sesion

app_name = 'users'

urlpatterns = [
    path('', Registro.as_view(), name='Usuarios'),
    path('cerrrar_sesion', cerrar_sesion, name='cerrar_sesion'),
    path('iniciar_sesion', iniciar_sesion, name='iniciar_sesion'),
]

shop/myshop/cart/forms.py
from django import forms

PRODUCTO_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCTO_QUANTITY_CHOICES, 
                                      coerce=int)

    override = forms.BooleanField(required=False, 
                                  initial=False, 
                                  widget= forms.HiddenInput)

shop/myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Producto
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, producto_id):
    cart = Cart(request)
    producto = get_object_or_404(Producto, id=producto_id)
    form = CartAddProductForm(request.POST)

    # Verificar la EXISTENCIA del producto antes de procesar el formulario
    if producto.existencias > 0:
        if form.is_valid():
            cd = form.cleaned_data
            # Restar la cantidad vendida del atributo existencias
            producto.existencias -= cd['quantity']
            producto.save()
            cart.add(producto=producto,
                    quantity=cd['quantity'],
                    override_quantity=cd['override'])
            return redirect('cart:cart_detalle')
    else:
        return redirect('shop:producto_detalle', producto.id, producto.slug)

   
@require_POST
def cart_remove(request, producto_id):
    cart = Cart(request)
    producto = get_object_or_404(Producto, id=producto_id)
     # Agregar la cantidad removida al atributo existencias
    producto.existencias += cart.cart[str(producto.id)]['quantity']
    producto.save()
    cart.remove(producto)
    return redirect('cart:cart_detalle')


def cart_detalle(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True})
        # Verificar la disponibilidad del producto y establecer una bandera para la plantilla
        item['disponible'] = item['producto'].existencias > 0
    return render(request, 'cart/detalle.html', {'cart': cart})

shop/myshop/cart/templates/cart/detalle.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    Carrito
{% endblock %}

{% block content %}
<!-- TÍTULO-->
    <h1>TODOS LOS PRODUCTOS</h1>
    
    <!-- TABLA PARA MOSTRAR TODOS LOS ELEMENTOS AGREGADOS AL CARRITO -->
    <table class="cart">
        <thead>
            <tr>
                <!-- TÍTULO DE LAS COLUMNAS-->
                <th>Imagen</th>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Eliminar</th>
                <th>Precio unitario</th>
                <th>Precio total</th>
            </tr>  
        </thead>
        <tbody>

            <!-- MOSTRAR LOS PRODUCTOS AGREGADOS AL CARRITO -->
            {% for item in cart %}
                {% with producto=item.producto %}
                    <tr>
                        <td>
                            <a href="{{ producto.get_absolute_url }}">
                                <img src="{% if producto.imagen %}{{ producto.imagen.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                            </a>
                        </td>
                        <td>{{ producto.nombre }}</td>
                        <td>
                            <!-- FORM PARA ACTUALZAR LOS PRODUCTOS SI ES QUE SE AGREGAN MÁS -->
                                <form action="{% url 'cart:cart_add' item.producto.id %}" method="post">
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.override }}
                                    <input type="submit" value="Actualizar">
                                    {% csrf_token %}
                                </form>
                        </td>
                        <td>
                            <!-- FORM PARA ELIMINAR PRODUCTOS -->
                            <form action="{% url 'cart:cart_remove' item.producto.id %}" method="post">
                                <input type="submit" value="Eliminar">
                                <!--<img src="{% static "images/actualizar.png" %}">-->
                                {% csrf_token %}
                            </form>
                        </td>
                        <!-- MOSTRAR LOS PRECIOS DE CADA PRODUCTO Y EL TOTAL -->
                        <td class="num">${{ item.precio }}</td>
                        <td class="num">${{ item.total_precio }}</td>
                            
                    </tr>
                {% endwith %}
            {% endfor %}
            <!-- MOSTRAR EL TOTAL DE LOS PRODUCTOS -->
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">${{ cart.get_total_precio }}</td>
            </tr>
        </tbody>
    </table>
    <!-- BOTONES PARA CONTINUAR CON LA COMPRA/ ORDENAR-->
    <p class="text-right">
        <a href="{% url "shop:producto_lista" %}" class="button light">Continuar compra</a>
        <!-- VERIFICAR SI EL USUARIO INICIO SESIÓN -->
        {% if user.is_authenticated %}
            <!-- SI EL USUARIO YA INICIO SESIÓN LO REDIRIGE A LA OTRA PESTAÑA -->
            <a href="{% url "orders:order_create" %}" class="button">Ordenar</a>
        {% else %}
            <!-- SI EL USUARIO NO HA INICIADO SESIÓN LO MANDA A INICIAR SESIÓN -->
            <a href="{% url "users:iniciar_sesion" %}" class="button">Iniciar sesión para ordenar</a>
        {% endif %}
    </p>
{% endblock %}