shop/myshop/cart/urls.py
from django.urls import path
from . import views

app_name ='cart'
urlpatterns=[
    path('', views.cart_detalle, name='cart_detalle'),
    path('add/<int:producto_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:producto_id>/', views.cart_remove, name='cart_remove'),
]

shop/myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='order')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/myshop/users/urls.py
from django.urls import path
from .views import Registro, cerrar_sesion, iniciar_sesion

app_name = 'users'

urlpatterns = [
    path('', Registro.as_view(), name='Usuarios'),
    path('cerrrar_sesion', cerrar_sesion, name='cerrar_sesion'),
    path('iniciar_sesion', iniciar_sesion, name='iniciar_sesion'),
]

shop/myshop/orders/models.py
from django.db import models
from django.contrib.auth import get_user_model
from shop.models import Producto

# Create your models here.

class Orden(models.Model):
    primer_nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    correo = models.EmailField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    pagado = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']
        indexes = [
        models.Index(fields=['-created']),
        ]

    def __str__(self):
        return f'Orden {self.id}'  
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    
class OrdenProductos(models.Model):
    orden = models.ForeignKey(Orden, related_name='items', on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, related_name='orden_items', on_delete=models.CASCADE)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad= models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)
    
    def get_cost(self):
        return self.precio * self.cantidad

shop/myshop/users/models.py
from django.db import models

shop/myshop/users/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages

# Create your views here.

class Registro(View):
    #muestra el formulario
    def get(self, request):
        form = UserCreationForm()
        return render(request, "registro/registro.html", {"form": form})

    #envio la información del formulario
    def post(self, request):
         form = UserCreationForm(request.POST)
         # VERIFICAR SI ES VALIDO LOS DATOS INTRODUCIDOS
         if form.is_valid():
            #guardar los datos del formulario en la variable usuario
            usuario = form.save(commit=False)
            primer_nombre = request.POST.get('primer_nombre')
            apellido = request.POST.get('apellido')
            correo = request.POST.get('correo')
            # Asignar los datos de órdenes al usuario
            usuario.first_name = primer_nombre
            usuario.last_name = apellido  # Asignar el apellido al campo last_name
            usuario.email = correo
            usuario.save()

            #login automatico
            login(request, usuario)
            #rediccionar a la página de inicio
            return redirect('shop:producto_lista')
         else:
            for msg in form.error_messages:
                messages.error(request, form.error_messages[msg])
            return render(request, "registro/registro.html", {"form": form})

#FUNCIÓN PARA CERRAR SESIÓN        
def cerrar_sesion(request):
    logout(request)
    return redirect("shop:producto_lista")

def iniciar_sesion(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():
            nombre_usuario = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            #verificar con la bd
            usuario = authenticate(username = nombre_usuario, password = password)
            #SI ENCUENTRA AL USUARIO LO MANDA A LA PÁGINA PRINCIPAL
            if usuario is not None:
                login(request, usuario)
                return redirect("shop:producto_lista")
            #SI NO LO ENCUENTRA AL USUARIO MOSTRAR
            else:
                messages.error(request, "usuario no encontrado")
        else:
            messages.error(request, "información incorrecta")
            
    form = AuthenticationForm()
    return render(request, "login/login.html", {"form": form})

shop/myshop/users/templates/registro/registro.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}

<!--CONTENEDOR PARA EL FORMULARIO-->
<div class="div-principal">
    <div class="div-inicio">
        <!--INCIO DE FORMULARIO-->
    <form class="form-order" method="POST">
        {% csrf_token %}
        <!--CONTENEDOR PARA INGRESAR EL NOMBRE DEL USUARIO-->
        <div>
            <!--LABEL PARA NOMBRE-->
            <label class="label-form" for="id_primer_nombre">Nombre:</label>
            <div>
                <!--INGRESAR NOMBRE-->
                <input type="text" id="id_primer_nombre" name="primer_nombre" maxlength="50" required="" class="input-form">  
            </div>
        </div>

        <!--CONTENEDOR PARA INGRESAR EL APELLIDO DEL USUARIO-->
        <div>
            <!--LABEL PARA APELLIDO-->
            <label class="label-form" for="id_apellido">Apellido:</label>
            <div>
                <!--INGRESAR APELLIDO-->
                <input type="text" id="id_apellido" name="apellido" maxlength="50" required="" class="input-form">  
            </div>
        </div>

        <!--CONTENEDOR PARA INGRESAR EL CORREO DEL USUARIO-->
        <div>
            <!--LABEL PARA CORREO-->
            <label class="label-form" for="id_correo">Correo:</label>
            <div>
                <!--INGRESAR CORREO-->
                <input type="email" id="id_correo" name="correo" maxlength="254" required="" class="input-form">  
            </div>
        </div>

        <!--CONTENEDOR PARA INGRESAR EL NOMBRE DE USUARIO-->
        <div>
            <!--LABEL PARA USUARIO-->
            <label class="label-form" for="id_username">Usuario:</label>
            <div>
                <!--INGRESAR NOMBRE DE USUARIO-->
                <input type="text" id="id_username" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" class="input-form">  
            </div>
        </div>

        <!--CONTENEDOR PARA INGRESAR LA CONTRASEÑA-->
        <div>
            <!--LABEL PARA CONTRASEÑA-->
            <label class="label-form" for="id_password1">Contraseña:</label>
            <div>
                <!--INGRESAR CONTRASEÑA-->
                <input type="password" id="id_password1" name="password1" autocomplete="new-password" required="" class="input-form">
            </div>
        </div>

        <!--CONTENEDOR PARA CONFIRMAR LA CONTRASEÑA-->
        <div>
            <!--LABEL PARA CONFIRMAR CONTRASEÑA-->
            <label class="label-form" for="id_password2">Confirmar contraseña:</label>
            <div>
                <!--INGRESAR CONTRASEÑA-->
                <input type="password" id="id_password2" name="password2" autocomplete="new-password" required="" class="input-form">
            </div>
        </div>

        <div class="errores">
            {% if form.errors %}
            <p>Error en el formulario:</p>
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
            {% endif %}
        </div>

        <!--BOTÓN PARA ENVIAR FORMULARIO-->
        <p><input type="submit" name="efectivo" value="Registrate"></p>
    </form>
    </div>
    
</div>

{% endblock %}